import type { TemplateDef } from '../types'

const BASE = import.meta.env.BASE_URL + 'templates/durazno-suave'

/**
 * Plantilla «Durazno Suave»: una foto principal apaisada arriba y dos fotos
 * circulares en la tarjeta, en tonos durazno suaves y modernos.
 */
export const duraznoSuave: TemplateDef = {
  id: 'durazno-suave',
  name: 'Durazno Suave',
  thumbnail: `${BASE}/thumbnail.svg`,
  version: 1,
  canvas: { width: 1200, height: 1800, bleedPx: 38, safePx: 38 },
  background: `${BASE}/background.svg`,
  overlays: [],
  photoSlots: [
    {
      id: 'foto-1',
      x: 90,
      y: 150,
      width: 1020,
      height: 510,
      rotation: 0,
      clipShape: 'rounded',
      cornerRadius: 18,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
    {
      id: 'foto-2',
      x: 330,
      y: 930,
      width: 240,
      height: 240,
      rotation: 0,
      clipShape: 'rounded',
      cornerRadius: 120,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
    {
      id: 'foto-3',
      x: 630,
      y: 930,
      width: 240,
      height: 240,
      rotation: 0,
      clipShape: 'rounded',
      cornerRadius: 120,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
  ],
  textFields: [
    {
      id: 'nombre',
      x: 100,
      y: 730,
      width: 1000,
      align: 'center',
      fontFamily: 'Great Vibes',
      fontSize: 100,
      color: '#d2755a',
      maxLines: 1,
      role: 'quinceaneraName',
      placeholder: 'Nombre de la quinceañera',
      sample: 'Chelsea Valentina',
    },
    {
      id: 'mensaje',
      x: 150,
      y: 1240,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 34,
      color: '#6b4a3e',
      maxLines: 2,
      role: 'message',
      placeholder: 'Mensaje de agradecimiento',
      sample: 'Gracias por acompañarme',
    },
    {
      id: 'negocio',
      x: 150,
      y: 1420,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 44,
      fontStyle: 'italic',
      color: '#c25a3a',
      maxLines: 2,
      role: 'businessName',
      placeholder: 'Nombre del negocio',
      sample: 'Videofilmaciones "Yesenia"',
    },
    {
      id: 'telefono',
      x: 150,
      y: 1570,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 38,
      fontStyle: 'bold',
      color: '#444444',
      maxLines: 1,
      role: 'phone',
      placeholder: 'Cel. 0000 00 00 00',
      sample: 'Cel. 6672 21 62 83',
    },
  ],
}
