import type { TemplateDef } from '../types'

const BASE = import.meta.env.BASE_URL + 'templates/lila-encanto'

/** Plantilla «Lila Encanto»: tres fotos en fila sobre lavanda + tarjeta. */
export const lilaEncanto: TemplateDef = {
  id: 'lila-encanto',
  name: 'Lila Encanto',
  thumbnail: `${BASE}/thumbnail.svg`,
  version: 1,
  canvas: { width: 1200, height: 1800, bleedPx: 38, safePx: 38 },
  background: `${BASE}/background.svg`,
  overlays: [],
  photoSlots: [
    {
      id: 'foto-1',
      x: 70,
      y: 160,
      width: 330,
      height: 440,
      rotation: -2,
      clipShape: 'rounded',
      cornerRadius: 14,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
    {
      id: 'foto-2',
      x: 435,
      y: 130,
      width: 330,
      height: 470,
      rotation: 0,
      clipShape: 'rounded',
      cornerRadius: 14,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
    {
      id: 'foto-3',
      x: 800,
      y: 160,
      width: 330,
      height: 440,
      rotation: 2,
      clipShape: 'rounded',
      cornerRadius: 14,
      frameStyle: 'thin',
      defaultFit: 'cover',
    },
  ],
  textFields: [
    {
      id: 'nombre',
      x: 100,
      y: 790,
      width: 1000,
      align: 'center',
      fontFamily: 'Great Vibes',
      fontSize: 112,
      color: '#7a3fa0',
      maxLines: 1,
      role: 'quinceaneraName',
      placeholder: 'Nombre de la quinceañera',
      sample: 'Chelsea Valentina',
    },
    {
      id: 'mensaje',
      x: 150,
      y: 1030,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 36,
      color: '#4a3a55',
      maxLines: 2,
      role: 'message',
      placeholder: 'Mensaje de agradecimiento',
      sample: 'Gracias por acompañarme',
    },
    {
      id: 'negocio',
      x: 150,
      y: 1240,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 46,
      fontStyle: 'italic',
      color: '#7a3fa0',
      maxLines: 2,
      role: 'businessName',
      placeholder: 'Nombre del negocio',
      sample: 'Videofilmaciones "Yesenia"',
    },
    {
      id: 'telefono',
      x: 150,
      y: 1420,
      width: 900,
      align: 'center',
      fontFamily: 'Playfair Display',
      fontSize: 40,
      fontStyle: 'bold',
      color: '#444444',
      maxLines: 1,
      role: 'phone',
      placeholder: 'Cel. 0000 00 00 00',
      sample: 'Cel. 6672 21 62 83',
    },
  ],
}
